package com.are.distribuidora.domain.model

import com.are.distribuidora.domain.valueobject.Quantity
import com.are.distribuidora.domain.valueobject.Money
import com.are.distribuidora.domain.valueobject.ProductId

/**
 * Modelo soberano de dominio.
 *
 * - No depende de Room/Firestore/Android.
 * - Representa la verdad del negocio para un producto en el catálogo.
 */
data class Product(
    val id: ProductId,
    val name: String,
    val description: String? = null,
    val category: String? = null,
    val price: Money,
    /** URL remota (https://...) de Firebase Storage. Campo autoritativo — coincide con Firestore "imageUrl". */
    val imageUrl: String? = null,
    /** URI local de la imagen (solo para renderizar en este dispositivo). */
    val imageLocalUri: String? = null,
    val barcode: String? = null,
    val stock: Quantity,
    /** Unidades pedidas que exceden el stock disponible. Default 0. */
    val comprometido: Int = 0,
    val isActive: Boolean = true,
    val isDeleted: Boolean = false,
    /**
     * createdAt is client-generated and is NOT authoritative.
     * It is used only for UI ordering and display.
     * Conflict resolution is based exclusively on updatedAt
     * generated by Firestore server timestamps.
     */
    val createdAt: Long,
    val updatedAt: Long,
) {

    init {
        require(name.isNotBlank()) { "name no puede estar vacío" }
    }

    fun canSell(quantity: Quantity): Boolean {
        require(!quantity.isZero()) { "quantity debe ser mayor que 0" }
        return stock >= quantity
    }

    fun sell(quantity: Quantity): Product {
        require(!quantity.isZero()) { "quantity debe ser mayor que 0" }
        return copy(stock = stock - quantity)
    }

    fun reserve(quantity: Quantity): Product =
        copy(stock = stock - quantity)

    fun release(quantity: Quantity): Product =
        copy(stock = stock + quantity)
}
