package com.are.distribuidora.data.repository

import android.util.Log
import com.are.distribuidora.core.images.FirestoreImageUrlValidator
import com.are.distribuidora.data.local.DistribuidoraDatabase
import com.are.distribuidora.data.local.SyncStatus
import com.are.distribuidora.data.local.dao.ProductDao
import com.are.distribuidora.data.mapper.toDomainOrNull
import com.are.distribuidora.data.mapper.toEntity
import com.are.distribuidora.data.remote.product.ProductRemoteDataSource
import com.are.distribuidora.data.remote.model.RemoteProduct
import com.are.distribuidora.domain.model.Product
import com.are.distribuidora.domain.product.ProductSyncRepository
import com.are.distribuidora.domain.valueobject.Money
import com.are.distribuidora.domain.valueobject.ProductId
import com.are.distribuidora.domain.valueobject.Quantity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.math.BigDecimal
import javax.inject.Inject
import com.are.distribuidora.data.storage.ProductImageStorage

private const val TAG = "SYNC_PRODUCT"

/**
 * Synchronization Policy:
 *
 * Conflict Resolution Strategy: Last-Write-Wins (LWW)
 * Authority: Firestore server timestamp
 * Comparison Key: updatedAt generated by server
 * Tie-breaker: Latest server timestamp wins
 * Granularity: Full entity replacement
 *
 * The client never generates authoritative timestamps.
 * All updatedAt values originate from Firestore.
 */
class ProductSyncRepositoryImpl @Inject constructor(
    private val remote: ProductRemoteDataSource,
    private val local: ProductDao,
    private val database: DistribuidoraDatabase,
    private val imageStorage: ProductImageStorage,
    private val pendingUploadDao: com.are.distribuidora.data.local.dao.PendingUploadDao,
    private val movementDao: com.are.distribuidora.stockmovement.data.local.dao.StockMovementDao,
    private val cursorStore: com.are.distribuidora.data.local.prefs.ProductSyncCursorStore,
) : ProductSyncRepository {

    /**
     * 4.1 — Stock local reconstruido en cada bajada:
     *   stock local = stock remoto + Σ movimientos locales aún NO subidos (con signo)
     *
     * El servidor solo conoce los movimientos que ya llegaron (cada uno aplicó su incremento
     * atómico). Los que siguen pendientes en este teléfono todavía no están en ese contador, así
     * que se suman aquí para que una venta sin subir no "desaparezca" cuando baja el catálogo.
     * Cuando esos movimientos se suben, el delta pendiente vuelve a 0 y el remoto ya los incluye:
     * converge sin escritura absoluta del contador. Si el remoto omite `stock`, se conserva el local.
     */
    private suspend fun reconcileStock(productId: String, remoteStock: Int?, existingLocalStock: Int?): Int {
        if (remoteStock == null) return existingLocalStock ?: 0
        return remoteStock + movementDao.sumPendingDelta(productId)
    }

    override suspend fun fetchRemoteProducts(): List<Product> = withContext(Dispatchers.IO) {
        // Delta Sync: Get max local timestamp
        // STRICT LWW: Only consider SYNCED products to avoid pollution from pending items
        val maxUpdatedAt = local.getMaxUpdatedAtSynced() ?: 0L
        Log.d(TAG, "fetchRemoteProducts: Local maxUpdatedAt = $maxUpdatedAt")

        val remoteProducts = mutableListOf<RemoteProduct>()
        remote.fetchProductsFlow(maxUpdatedAt, null).collect {
            remoteProducts.addAll(it)
        }

        Log.d(TAG, "fetchRemoteProducts: Remote returned ${remoteProducts.size} products")

        if (remoteProducts.isNotEmpty()) {
            val ids = remoteProducts.take(10).joinToString { it.id }
            Log.d(TAG, "fetchRemoteProducts: First IDs = [$ids...]")
        }

        remoteProducts.mapNotNull { r ->
            try {
                // Map Remote -> Domain
                val remoteImageUrl = r.imageUrl?.takeIf { it.startsWith("http://") || it.startsWith("https://") }
                // CRITERION C: a missing remote field must never zero-out local data.
                // Preserve the current local stock when the remote doc omits it
                // (e.g. a partial/merge write by another process).
                val existing = local.getById(r.id)
                Product(
                    id = ProductId.of(r.id),
                    name = r.name,
                    description = r.description,
                    category = r.category,
                    price = Money.of(BigDecimal.valueOf(r.price ?: 0.0)),
                    imageUrl = remoteImageUrl,
                    imageLocalUri = null,
                    barcode = r.barcode,
                    stock = Quantity.of(reconcileStock(r.id, r.stock, existing?.stock)),
                    isActive = r.isActive ?: true,
                    isDeleted = r.isDeleted ?: false,
                    createdAt = r.createdRemoteAt ?: 0L,
                    updatedAt = r.updatedRemoteAt ?: 0L,
                )
            } catch (e: Exception) {
                Log.e(TAG, "Error mapping remote product ${r.id}", e)
                null
            }
        }
    }

    override suspend fun saveLocalProducts(products: List<Product>) {
        if (products.isEmpty()) {
            Log.d(TAG, "saveLocalProducts: No products to save")
            return
        }

        Log.d(TAG, "saveLocalProducts: Saving ${products.size} remote products")

        withContext(Dispatchers.IO) {
            database.runInTransaction {
                Log.d(TAG, "saveLocalProducts: Entered transaction")
                val now = System.currentTimeMillis()
                
                products.forEach { product ->
                    try {
                        // STRICT LWW: We mostly treat deleted/active same way via SyncStatus.SYNCED
                        // logic is intertwined with SyncStatus and isDeleted usage.
                        
                        val entity = product.toEntity(SyncStatus.SYNCED).copy(
                            lastSyncedAt = now
                        )
                        
                        val existing = local.getById(product.id.value)
                        
                        if (existing == null) {
                            if (product.isDeleted) {
                                Log.d(TAG, "saveLocalProducts: Remote product ${product.id.value} is deleted and doe not exist locally. Skipping insert.")
                            } else {
                                Log.d(TAG, "saveLocalProducts: Inserting new product ${product.id.value}")
                                local.insert(entity)
                            }
                        } else {
                            // CRITERION A: never overwrite a not-yet-durably-synced local row.
                            // Only a durably SYNCED local row may be replaced by remote data.
                            // Any other state (PENDING_*/SYNCING/CONFLICT/legacy) carries
                            // un-uploaded local intent and must survive the downsync.
                            if (existing.syncStatus != SyncStatus.SYNCED) {
                                Log.d(TAG, "saveLocalProducts: PROTECT local ${product.id.value} (syncStatus=${existing.syncStatus}); skipping remote overwrite")
                                return@forEach
                            }

                            // STRICT LWW CHECK
                            // Authority: Server via product.updatedAt
                            Log.d(TAG, "saveLocalProducts: Comparing remote(${product.updatedAt}) vs local(${existing.updatedAt}) for ${product.id.value}")

                            // HARD DELETE ON DOWNSTREAM SYNC
                            // If remote says it is deleted, we NUKE it locally.
                            if (product.isDeleted) {
                                if (product.updatedAt >= existing.updatedAt) {
                                    Log.d(TAG, "saveLocalProducts: Remote is DELETED and newer/equal. Performing HARD DELETE on ${product.id.value}")
                                    local.deleteInternal(product.id.value)
                                } else {
                                    Log.d(TAG, "saveLocalProducts: Remote is DELETED but older. Ignoring delete for ${product.id.value}")
                                }
                                return@forEach
                            }

                            if (product.updatedAt >= existing.updatedAt) {
                                // Remote is newer or equal -> Wins
                                // Full replacement of fields (including isActive)
                                Log.d(TAG, "saveLocalProducts: Remote wins → updating ${product.id.value}")
                                local.update(entity) 
                            } else {
                                Log.d(TAG, "saveLocalProducts: Local wins → ignoring ${product.id.value} (local ${existing.updatedAt} > remote ${product.updatedAt})")
                            }
                        }
                    } catch (e: Exception) {
                        Log.e(TAG, "saveLocalProducts: Error saving product ${product.id.value}", e)
                    }
                }

                Log.d(TAG, "saveLocalProducts: Transaction completed")
            }
        }
    }

    override suspend fun uploadPendingProducts() {
        // 1. Recuperación de Crash: Si la app murió en medio de un sync,
        // reseteamos cualquier SYNCING a su PENDING correspondiente.
        // Nota: esto queda como fallback defensivo; el flujo por-item debe revertir inmediatamente ante fallos.
        local.resetStaleSyncingToPending()

        withContext(Dispatchers.IO) {
            val pending = local.getPending(
                listOf(
                    SyncStatus.PENDING_CREATE,
                    SyncStatus.PENDING_UPDATE,
                    SyncStatus.PENDING_DELETE
                ),
                limit = 50
            )

            Log.d(TAG, "uploadPendingProducts: Found ${pending.size} pending products to upload")

            pending.forEach { entity ->
                var synced = false
                try {
                    val operationType = when (entity.syncStatus) {
                        SyncStatus.PENDING_CREATE -> "CREATE"
                        SyncStatus.PENDING_UPDATE -> "UPDATE"
                        SyncStatus.PENDING_DELETE -> "DELETE"
                        else -> "UNKNOWN"
                    }
                    Log.d(TAG, "[Pipeline] Start upload pipeline for ${entity.id} - Op=$operationType")

                    // Mark as Syncing
                    Log.d(TAG, "[Pipeline] ${entity.id} -> Marking SYNCING locally")
                    local.markSyncing(entity.id)

                    val domain = entity.toDomainOrNull()
                    if (domain == null) {
                        // NO dejar SYNCING colgado por errores de mapping/validacin.
                        Log.e(TAG, "[Pipeline] ${entity.id} mapping to domain returned null. Reverting to pending.")
                        local.revertSyncingToPending(entity.id)
                        return@forEach
                    }

                    // --- Imagen OFFLINE-FIRST ---
                    // La subida de imágenes se maneja por UploadPendingProductImagesWorker.
                    // Aquí solo usamos imageUrl si ya fue subida (https://...).
                    // Si imageUrl es null o local, enviamos null a Firestore.
                    // NUNCA enviamos rutas locales a Firestore.

                    // FIX: Re-leer imageUrl fresco desde Room para capturar si el
                    // ImageWorker ya actualizó la URL remota entre que se leyó el
                    // batch y este momento.
                    val freshEntity = local.getById(entity.id)
                    val latestImageUrl = freshEntity?.imageUrl ?: entity.imageUrl
                    val effectiveImageUrl = latestImageUrl
                        ?.takeIf { it.startsWith("http://") || it.startsWith("https://") }

                    // Check si hay un upload de imagen pendiente para este producto
                    val pendingUpload = pendingUploadDao.findByEntityId(entity.id)
                    val hasPendingImageUpload = pendingUpload
                        ?.let { it.state == "PENDING" || it.state == "UPLOADING" || it.state == "FAILED" }
                        ?: false

                    if (hasPendingImageUpload) {
                        Log.d(TAG, "[Pipeline] ${entity.id} has pending image upload (state=${pendingUpload?.state}). imageUrl will be ${if (effectiveImageUrl != null) effectiveImageUrl else "null (excluded from payload)"}")
                    }

                    // Validación G: bloquear rutas locales a Firestore
                    FirestoreImageUrlValidator.validateForFirestore(effectiveImageUrl)

                    val remoteProduct = RemoteProduct(
                        id = domain.id.value,
                        name = domain.name,
                        description = domain.description,
                        category = domain.category,
                        price = domain.price.amount.toDouble(),
                        imageUrl = effectiveImageUrl,
                        barcode = domain.barcode,
                        // 4.1: el stock NO se sube como valor absoluto (null = omitido). El
                        // contador remoto solo lo mueven los movimientos con increment().
                        stock = null,
                        isActive = entity.isActive,
                        isDeleted = entity.isDeleted,
                        createdRemoteAt = domain.createdAt,
                        updatedRemoteAt = null // SERVER AUTHORITY
                    )

                    // Payload Summary Log
                    Log.d(
                        TAG,
                        "[Pipeline] Payload for ${entity.id}: isActive=${remoteProduct.isActive}, isDeleted=${remoteProduct.isDeleted} (stock omitido: solo movimientos)"
                    )

                    if (entity.syncStatus == SyncStatus.PENDING_DELETE) {
                        val neverSynced = (entity.lastSyncedAt == null || entity.lastSyncedAt == 0L)

                        if (neverSynced) {
                            Log.i(
                                TAG,
                                "[Pipeline] ${entity.id} pending delete + neverSynced. Hard-deleting locally (no remote call)."
                            )
                            local.deleteInternal(entity.id)
                            // Row removed => nothing to revert/markSynced.
                            synced = true
                            return@forEach
                        } else {
                            Log.d(TAG, "[Pipeline] ${entity.id} -> Soft deleting remotely")
                            remote.softDeleteProduct(entity.id, entity.updatedAt)
                        }
                    } else {
                        Log.d(TAG, "[Pipeline] ${entity.id} -> Uploading to remote")
                        remote.uploadProduct(remoteProduct)
                    }

                    Log.d(TAG, "[Pipeline] Remote upload success for ${entity.id}")

                    // Mark as Synced adoptando el updatedAt (y el stock) del SERVIDOR.
                    // Sin esto el cursor de bajada (MAX(updatedAt) de los SYNCED) podía quedar
                    // por delante del reloj del servidor y el teléfono dejaba de recibir cambios
                    // de stock sin ningún error (auditoría 2026-09-03, hallazgo 1).
                    val now = System.currentTimeMillis()
                    val snapshot = try {
                        remote.fetchProductById(entity.id)
                    } catch (e: Exception) {
                        Log.w(TAG, "[Pipeline] ${entity.id} snapshot remoto no disponible (${e.message}); se conserva updatedAt local")
                        null
                    }
                    val serverUpdatedAt = snapshot?.updatedRemoteAt?.takeIf { it > 0L }
                    val reconciledStock = snapshot?.let { reconcileStock(entity.id, it.stock, entity.stock) }
                    Log.d(TAG, "[Pipeline] ${entity.id} -> Marking SYNCED lastSyncedAt=$now serverUpdatedAt=$serverUpdatedAt stock=$reconciledStock")

                    local.markSynced(
                        id = entity.id,
                        lastSyncedAt = now,
                        serverUpdatedAt = serverUpdatedAt,
                        stock = reconciledStock,
                    )
                    synced = true
                    Log.d(TAG, "uploadPendingProducts: Successfully synced ${entity.id}")
                } catch (e: Exception) {
                    Log.e(TAG, "[Pipeline] Error uploading product ${entity.id}. Reverting to pending.", e)
                    // Revert inmediato por-item (NO esperar a reset global)
                    try {
                        local.revertSyncingToPending(entity.id)
                    } catch (revertError: Exception) {
                        Log.e(TAG, "[Pipeline] Failed to revert SYNCING->PENDING for ${entity.id}", revertError)
                    }
                } finally {
                    // Garanta fuerte: si marcamos SYNCING y no completamos (markSynced/delete), revertimos.
                    if (!synced) {
                        try {
                            local.revertSyncingToPending(entity.id)
                            Log.d(TAG, "[Pipeline] ${entity.id} -> Reverted to pending (finally safeguard)")
                        } catch (e: Exception) {
                            Log.e(TAG, "[Pipeline] ${entity.id} -> Failed final revert safeguard", e)
                        }
                    }
                }
            }

            Log.d(TAG, "uploadPendingProducts: Upload batch completed")
        }
    }

    override suspend fun syncDownstream() = withContext(Dispatchers.IO) {
        // ── El watermark de bajada NO puede salir de la tabla `products` ──────────────
        // `MAX(updatedAt)` de las filas SYNCED responde "cuál es el sello más nuevo que tengo",
        // no "hasta dónde bajé". Al subir un producto adoptamos el `updatedAt` que le asigna el
        // servidor, así que ese máximo SALTA: cualquier documento que otro teléfono escribió en
        // medio (el vale que mueve `stock` con increment) queda por debajo del cursor y no se
        // descarga NUNCA — el stock nuevo no llega y el watermark deja de moverse. Ver
        // ProductSyncCursorStore.
        val maxUpdatedAt = cursorStore.get() ?: 0L
        val lastId = local.getLastSyncedProduct()?.id

        Log.d(TAG, "syncDownstream: Starting downstream sync from timestamp=$maxUpdatedAt, lastId=$lastId")

        var totalUpdated = 0
        var totalProtected = 0
        var totalStale = 0
        var totalBatches = 0
        val startTime = System.currentTimeMillis()

        // 1. Phased Download: Consume Flow
        // Flow handles pagination internally (updatedAt + ID cursor)
        try {
            remote.fetchProductsFlow(maxUpdatedAt, lastId)
                .collect { batch ->
                    if (batch.isEmpty()) return@collect
                    totalBatches++

                    Log.d(TAG, "syncDownstream: Processing batch #$totalBatches of ${batch.size} products")

                    // 2. Transactional Persistence (Batch Atomicity)
                    try {
                        database.runInTransaction {
                            val now = System.currentTimeMillis()
                            var batchDocsUpdated = 0
                            var batchProtected = 0
                            var batchStale = 0

                            batch.forEach { r ->
                                try {
                                    val existing = local.getById(r.id)

                                    // ── CRITERION A: PROTECT NOT-YET-DURABLY-SYNCED LOCAL ROWS ──
                                    // A local row may be overwritten by remote data ONLY if it is
                                    // brand-new (existing == null) or durably SYNCED. Any other
                                    // state — PENDING_CREATE / PENDING_UPDATE / PENDING_DELETE /
                                    // SYNCING / CONFLICT / legacy — carries un-uploaded local intent
                                    // and MUST NOT be reverted by a downsync, regardless of
                                    // timestamps (this closes the equal-timestamp tie that used to
                                    // let stale remote data win and silently revert the user's edit).
                                    //
                                    // We deliberately do NOT transition these rows to CONFLICT:
                                    // nothing in the app resolves a CONFLICT row and getPending()
                                    // never uploads it, so doing so would trap the user's edit
                                    // forever and break convergence. Keeping the row in its PENDING
                                    // state lets uploadPendingProducts() push it; it then converges
                                    // to SYNCED with a fresh server timestamp (Last-Write-Wins).
                                    if (existing != null && existing.syncStatus != SyncStatus.SYNCED) {
                                        Log.d(TAG, "syncDownstream: PROTECT local ${r.id} (syncStatus=${existing.syncStatus}); skipping remote overwrite")
                                        batchProtected++
                                        return@forEach
                                    }

                                    // From here: existing is null (new) or durably SYNCED (clean).
                                    // HARD DELETE: if remote says deleted and is newer/equal, nuke local.
                                    if (r.isDeleted == true) {
                                         // Check timestamps if existing
                                         val remoteUpdatedAt = r.updatedRemoteAt ?: 0L
                                         val localUpdatedAt = existing?.updatedAt ?: 0L

                                         if (existing != null && remoteUpdatedAt >= localUpdatedAt) {
                                              Log.d(TAG, "syncDownstream: Remote is DELETED and newer. Performing HARD DELETE on ${r.id}")
                                              local.deleteInternal(r.id)
                                              batchDocsUpdated++ // Count as a change
                                         } else if (existing == null) {
                                              Log.d(TAG, "syncDownstream: Remote is DELETED and not local. Skipping.")
                                         } else {
                                              Log.d(TAG, "syncDownstream: Remote is DELETED but older. Ignoring.")
                                         }
                                         return@forEach
                                    }

                                    // El contador solo cuenta ESCRITURAS REALES. Antes se
                                    // incrementaba siempre, incluso cuando saveRemoteProductToLocal
                                    // descartaba el write por LWW, así que el log `Updated=N` no era
                                    // evidencia de que se hubiera escrito nada y despistaba el
                                    // diagnóstico del downsync.
                                    if (saveRemoteProductToLocal(r, existing, now)) {
                                        batchDocsUpdated++
                                    } else {
                                        batchStale++
                                    }

                                } catch (e: Exception) {
                                    Log.e(TAG, "Error processing item ${r.id} in batch", e)
                                    throw e // Trigger transaction rollback for this batch
                                }
                            }
                            totalUpdated += batchDocsUpdated
                            totalProtected += batchProtected
                            totalStale += batchStale
                            Log.d(TAG, "syncDownstream: Batch committed. Updated=$batchDocsUpdated, Protected=$batchProtected, StaleIgnored=$batchStale")
                        }
                    } catch (e: Exception) {
                         Log.e(TAG, "Batch transaction failed", e)
                         throw e
                    }

                    // Solo una bajada REALMENTE aplicada mueve el watermark, y solo hasta el sello
                    // más alto del lote ya commiteado (los lotes llegan en orden ascendente). Si el
                    // proceso muere antes de esta línea, el siguiente ciclo vuelve a bajar el lote:
                    // es idempotente (LWW) y nunca deja un hueco.
                    batch.mapNotNull { it.updatedRemoteAt }.maxOrNull()?.let { cursorStore.advanceTo(it) }
                }
        } finally {
            val duration = System.currentTimeMillis() - startTime
            Log.i(TAG, "syncDownstream: Completed. Duration=${duration}ms, Batches=$totalBatches, Updated=$totalUpdated, Protected=$totalProtected, StaleIgnored=$totalStale")
        }
    }

    /**
     * @return true si REALMENTE se escribió la fila (insert o update); false si el write se
     * descartó (LWW: el remoto es más viejo que lo local, o llamada defensiva con isDeleted).
     * El contador `Updated=` del log depende de este booleano: contar intentos en vez de
     * escrituras hacía que un downsync que no aplicaba nada se reportara como exitoso.
     */
    private suspend fun saveRemoteProductToLocal(r: RemoteProduct, existing: com.are.distribuidora.data.local.entity.ProductEntity?, now: Long): Boolean {
        if (r.isDeleted == true) {
            // Should have been handled by caller, but safety check.
            Log.w(TAG, "saveRemoteProductToLocal called with isDeleted=true. Ignoring to prevent resurrection.")
            return false
        }

        // Remote imageUrl is always the authoritative remote URL (https://...), pero solo
        // vale si se puede mostrar: una de drive.google.com es un 404 permanente.
        val remoteImageUrl = FirestoreImageUrlValidator.usableForDisplayOrNull(r.imageUrl)

        // Proteger imageUrl contra sobreescritura con null.
        // Si el remoto no trae imageUrl pero localmente ya tenemos una URL válida
        // (subida por UploadPendingProductImagesWorker), NO sobrescribir con null.
        // Esto cubre el caso donde el product sync usó merge() y no envió imageUrl,
        // pero el ImageWorker ya actualizó Room con la URL real.
        //
        // IMPORTANTE: el guard preserva solo lo que la app considera UTILIZABLE. Con el
        // `startsWith("http")` de antes, poner `imageUrl` a null en Firestore no servía de
        // nada: el teléfono resucitaba su URL muerta de Drive en cada bajada y seguía
        // pidiéndola para siempre. Ahora el remoto sí puede borrar la imagen, y solo
        // sobrevive una de Storage que de verdad carga.
        val preservableLocalImageUrl =
            FirestoreImageUrlValidator.usableForDisplayOrNull(existing?.imageUrl)
        val finalImageUrl = remoteImageUrl ?: preservableLocalImageUrl

        if (finalImageUrl != remoteImageUrl) {
            Log.d(TAG, "saveRemoteProductToLocal: Preserved local imageUrl for ${r.id} (remote was null, local=${finalImageUrl})")
        }
        if (finalImageUrl == null && existing?.imageUrl != null) {
            Log.i(TAG, "saveRemoteProductToLocal: Cleared unusable local imageUrl for ${r.id} (was=${existing.imageUrl})")
        }

         val entity = com.are.distribuidora.data.local.entity.ProductEntity(
            id = r.id,
            name = r.name,
            description = r.description,
            category = r.category,
            price = r.price ?: 0.0,
            imageUrl = finalImageUrl,
            imageLocalUri = existing?.imageLocalUri, // Preserve local URI if exists
            barcode = r.barcode,
            // CRITERION C: never zero stock just because the remote doc omits the field
            // (e.g. a partial/merge write by another process). Preserve the local value.
            // 4.1: stock local = remoto + movimientos pendientes (ver reconcileStock).
            stock = reconcileStock(r.id, r.stock, existing?.stock),
            isActive = r.isActive ?: true,
            isDeleted = r.isDeleted ?: false,
            syncStatus = SyncStatus.SYNCED,
            createdAt = r.createdRemoteAt ?: 0L,
            updatedAt = r.updatedRemoteAt ?: 0L,
            lastSyncedAt = now
        )

        if (existing == null) {
            local.insert(entity)
            return true
        }
        // Caller guarantees `existing` is durably SYNCED here (dirty rows are protected
        // upstream). Strict LWW: newest server timestamp wins; ties resolve to remote.
        return if (entity.updatedAt >= existing.updatedAt) {
            local.update(entity)
            true
        } else {
            Log.d(TAG, "Msg: Ignored stale remote update for ${r.id} (remote=${entity.updatedAt} < local=${existing.updatedAt})")
            false
        }
    }
}
