package com.are.distribuidora.data.repository

import android.util.Log
import com.are.distribuidora.core.images.ProductImageUrl
import com.are.distribuidora.data.local.DistribuidoraDatabase
import com.are.distribuidora.data.local.SyncStatus
import com.are.distribuidora.data.local.dao.ProductDao
import com.are.distribuidora.data.mapper.toDomainOrNull
import com.are.distribuidora.data.mapper.toEntity
import com.are.distribuidora.data.remote.product.ProductRemoteDataSource
import com.are.distribuidora.data.remote.model.RemoteProduct
import com.are.distribuidora.domain.model.Product
import com.are.distribuidora.domain.product.ProductSyncRepository
import com.are.distribuidora.domain.valueobject.Money
import com.are.distribuidora.domain.valueobject.ProductId
import com.are.distribuidora.domain.valueobject.Quantity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.math.BigDecimal
import javax.inject.Inject
import com.are.distribuidora.data.storage.ProductImageStorage
import java.io.File

private const val TAG = "SYNC_PRODUCT"

/**
 * Synchronization Policy:
 *
 * Conflict Resolution Strategy: Last-Write-Wins (LWW)
 * Authority: Firestore server timestamp
 * Comparison Key: updatedAt generated by server
 * Tie-breaker: Latest server timestamp wins
 * Granularity: Full entity replacement
 *
 * The client never generates authoritative timestamps.
 * All updatedAt values originate from Firestore.
 */
class ProductSyncRepositoryImpl @Inject constructor(
    private val remote: ProductRemoteDataSource,
    private val local: ProductDao,
    private val database: DistribuidoraDatabase,
    private val imageStorage: ProductImageStorage,
) : ProductSyncRepository {

    override suspend fun fetchRemoteProducts(): List<Product> = withContext(Dispatchers.IO) {
        // Delta Sync: Get max local timestamp
        // STRICT LWW: Only consider SYNCED products to avoid pollution from pending items
        val maxUpdatedAt = local.getMaxUpdatedAtSynced() ?: 0L
        Log.d(TAG, "fetchRemoteProducts: Local maxUpdatedAt = $maxUpdatedAt")

        val remoteProducts = mutableListOf<RemoteProduct>()
        remote.fetchProductsFlow(maxUpdatedAt, null).collect {
            remoteProducts.addAll(it)
        }

        Log.d(TAG, "fetchRemoteProducts: Remote returned ${remoteProducts.size} products")

        if (remoteProducts.isNotEmpty()) {
            val ids = remoteProducts.take(10).joinToString { it.id }
            Log.d(TAG, "fetchRemoteProducts: First IDs = [$ids...]")
        }

        remoteProducts.mapNotNull { r ->
            try {
                // Map Remote -> Domain
                Product(
                    id = ProductId.of(r.id),
                    name = r.name,
                    description = r.description,
                    category = r.category,
                    price = Money.of(BigDecimal.valueOf(r.price ?: 0.0)),
                    imageUrl = r.imageUrl,
                    barcode = r.barcode,
                    stock = Quantity.of(r.stock ?: 0),
                    isActive = r.isActive ?: true, // Map isActive from remote
                    isDeleted = r.isDeleted ?: false,
                    createdAt = r.createdRemoteAt ?: 0L,
                    updatedAt = r.updatedRemoteAt ?: 0L,
                )
            } catch (e: Exception) {
                Log.e(TAG, "Error mapping remote product ${r.id}", e)
                null
            }
        }
    }

    override suspend fun saveLocalProducts(products: List<Product>) {
        if (products.isEmpty()) {
            Log.d(TAG, "saveLocalProducts: No products to save")
            return
        }

        Log.d(TAG, "saveLocalProducts: Saving ${products.size} remote products")

        withContext(Dispatchers.IO) {
            database.runInTransaction {
                Log.d(TAG, "saveLocalProducts: Entered transaction")
                val now = System.currentTimeMillis()
                
                products.forEach { product ->
                    try {
                        // STRICT LWW: We mostly treat deleted/active same way via SyncStatus.SYNCED
                        // logic is intertwined with SyncStatus and isDeleted usage.
                        
                        val entity = product.toEntity(SyncStatus.SYNCED).copy(
                            lastSyncedAt = now
                        )
                        
                        val existing = local.getById(product.id.value)
                        
                        if (existing == null) {
                            if (product.isDeleted) {
                                Log.d(TAG, "saveLocalProducts: Remote product ${product.id.value} is deleted and doe not exist locally. Skipping insert.")
                            } else {
                                Log.d(TAG, "saveLocalProducts: Inserting new product ${product.id.value}")
                                local.insert(entity)
                            }
                        } else {
                            // STRICT LWW CHECK
                            // Authority: Server via product.updatedAt
                            Log.d(TAG, "saveLocalProducts: Comparing remote(${product.updatedAt}) vs local(${existing.updatedAt}) for ${product.id.value}")
                            
                            // HARD DELETE ON DOWNSTREAM SYNC
                            // If remote says it is deleted, we NUKE it locally.
                            if (product.isDeleted) {
                                if (product.updatedAt >= existing.updatedAt) {
                                    Log.d(TAG, "saveLocalProducts: Remote is DELETED and newer/equal. Performing HARD DELETE on ${product.id.value}")
                                    local.deleteInternal(product.id.value)
                                } else {
                                    Log.d(TAG, "saveLocalProducts: Remote is DELETED but older. Ignoring delete for ${product.id.value}")
                                }
                                return@forEach
                            }

                            if (product.updatedAt >= existing.updatedAt) {
                                // Remote is newer or equal -> Wins
                                // Full replacement of fields (including isActive)
                                Log.d(TAG, "saveLocalProducts: Remote wins → updating ${product.id.value}")
                                local.update(entity) 
                            } else {
                                Log.d(TAG, "saveLocalProducts: Local wins → ignoring ${product.id.value} (local ${existing.updatedAt} > remote ${product.updatedAt})")
                            }
                        }
                    } catch (e: Exception) {
                        Log.e(TAG, "saveLocalProducts: Error saving product ${product.id.value}", e)
                    }
                }

                Log.d(TAG, "saveLocalProducts: Transaction completed")
            }
        }
    }

    override suspend fun uploadPendingProducts() {
        // 1. Recuperación de Crash: Si la app murió en medio de un sync,
        // reseteamos cualquier SYNCING a su PENDING correspondiente.
        // Nota: esto queda como fallback defensivo; el flujo por-item debe revertir inmediatamente ante fallos.
        local.resetStaleSyncingToPending()

        withContext(Dispatchers.IO) {
            val pending = local.getPending(
                listOf(
                    SyncStatus.PENDING_CREATE,
                    SyncStatus.PENDING_UPDATE,
                    SyncStatus.PENDING_DELETE
                ),
                limit = 50
            )

            Log.d(TAG, "uploadPendingProducts: Found ${pending.size} pending products to upload")

            pending.forEach { entity ->
                var synced = false
                try {
                    val operationType = when (entity.syncStatus) {
                        SyncStatus.PENDING_CREATE -> "CREATE"
                        SyncStatus.PENDING_UPDATE -> "UPDATE"
                        SyncStatus.PENDING_DELETE -> "DELETE"
                        else -> "UNKNOWN"
                    }
                    Log.d(TAG, "[Pipeline] Start upload pipeline for ${entity.id} - Op=$operationType")

                    // Mark as Syncing
                    Log.d(TAG, "[Pipeline] ${entity.id} -> Marking SYNCING locally")
                    local.markSyncing(entity.id)

                    val domain = entity.toDomainOrNull()
                    if (domain == null) {
                        // NO dejar SYNCING colgado por errores de mapping/validacin.
                        Log.e(TAG, "[Pipeline] ${entity.id} mapping to domain returned null. Reverting to pending.")
                        local.revertSyncingToPending(entity.id)
                        return@forEach
                    }

                    // --- Imagen OFFLINE-FIRST (Opción B) ---
                    // Si el producto tiene local://..., subimos a Storage antes de construir el payload.
                    // Si falla, dejamos local:// para reintento en el siguiente ciclo.
                    var effectiveImageUrl = domain.imageUrl
                    val localPath = ProductImageUrl.localPathOrNull(effectiveImageUrl)
                    if (localPath != null) {
                        try {
                            val file = File(localPath)
                            if (file.exists()) {
                                val downloadUrl = imageStorage.uploadMainImage(domain.id.value, file)
                                // Persistir reemplazo local (NO tocar SyncStatus, solo imageUrl)
                                local.updateImageUrl(entity.id, downloadUrl)
                                effectiveImageUrl = downloadUrl
                                Log.d(TAG, "[Pipeline] ${entity.id} image uploaded. Replaced local:// with remote url")
                            } else {
                                Log.w(TAG, "[Pipeline] ${entity.id} local image file not found at $localPath. Keeping local://")
                            }
                        } catch (e: Exception) {
                            Log.e(TAG, "[Pipeline] ${entity.id} image upload failed. Will retry next sync.", e)
                            // Mantener local:// intacto.
                        }
                    }

                    val remoteProduct = RemoteProduct(
                        id = domain.id.value,
                        name = domain.name,
                        description = domain.description,
                        category = domain.category,
                        price = domain.price.amount.toDouble(),
                        imageUrl = effectiveImageUrl,
                        barcode = domain.barcode,
                        stock = domain.stock.value,
                        comprometido = 0,
                        isActive = entity.isActive,
                        isDeleted = entity.isDeleted,
                        createdRemoteAt = domain.createdAt,
                        updatedRemoteAt = null // SERVER AUTHORITY
                    )

                    // Payload Summary Log
                    Log.d(
                        TAG,
                        "[Pipeline] Payload for ${entity.id}: isActive=${remoteProduct.isActive}, isDeleted=${remoteProduct.isDeleted}, stock=${remoteProduct.stock}"
                    )

                    if (entity.syncStatus == SyncStatus.PENDING_DELETE) {
                        val neverSynced = (entity.lastSyncedAt == null || entity.lastSyncedAt == 0L)

                        if (neverSynced) {
                            Log.i(
                                TAG,
                                "[Pipeline] ${entity.id} pending delete + neverSynced. Hard-deleting locally (no remote call)."
                            )
                            local.deleteInternal(entity.id)
                            // Row removed => nothing to revert/markSynced.
                            synced = true
                            return@forEach
                        } else {
                            Log.d(TAG, "[Pipeline] ${entity.id} -> Soft deleting remotely")
                            remote.softDeleteProduct(entity.id, entity.updatedAt)
                        }
                    } else {
                        Log.d(TAG, "[Pipeline] ${entity.id} -> Uploading to remote")
                        remote.uploadProduct(remoteProduct)
                    }

                    Log.d(TAG, "[Pipeline] Remote upload success for ${entity.id}")

                    // Mark as Synced
                    val now = System.currentTimeMillis()
                    Log.d(TAG, "[Pipeline] ${entity.id} -> Marking SYNCED with lastSyncedAt=$now")

                    local.markSynced(
                        id = entity.id,
                        lastSyncedAt = now
                    )
                    synced = true
                    Log.d(TAG, "uploadPendingProducts: Successfully synced ${entity.id}")
                } catch (e: Exception) {
                    Log.e(TAG, "[Pipeline] Error uploading product ${entity.id}. Reverting to pending.", e)
                    // Revert inmediato por-item (NO esperar a reset global)
                    try {
                        local.revertSyncingToPending(entity.id)
                    } catch (revertError: Exception) {
                        Log.e(TAG, "[Pipeline] Failed to revert SYNCING->PENDING for ${entity.id}", revertError)
                    }
                } finally {
                    // Garanta fuerte: si marcamos SYNCING y no completamos (markSynced/delete), revertimos.
                    if (!synced) {
                        try {
                            local.revertSyncingToPending(entity.id)
                            Log.d(TAG, "[Pipeline] ${entity.id} -> Reverted to pending (finally safeguard)")
                        } catch (e: Exception) {
                            Log.e(TAG, "[Pipeline] ${entity.id} -> Failed final revert safeguard", e)
                        }
                    }
                }
            }

            Log.d(TAG, "uploadPendingProducts: Upload batch completed")
        }
    }

    override suspend fun syncDownstream() = withContext(Dispatchers.IO) {
        val lastSyncedProduct = local.getLastSyncedProduct()
        val maxUpdatedAt = lastSyncedProduct?.updatedAt ?: 0L
        val lastId = lastSyncedProduct?.id

        Log.d(TAG, "syncDownstream: Starting downstream sync from timestamp=$maxUpdatedAt, lastId=$lastId")

        var totalUpdated = 0
        var totalConflicts = 0
        var totalBatches = 0
        val startTime = System.currentTimeMillis()

        // 1. Phased Download: Consume Flow
        // Flow handles pagination internally (updatedAt + ID cursor)
        try {
            remote.fetchProductsFlow(maxUpdatedAt, lastId)
                .collect { batch ->
                    if (batch.isEmpty()) return@collect
                    totalBatches++

                    Log.d(TAG, "syncDownstream: Processing batch #$totalBatches of ${batch.size} products")

                    // 2. Transactional Persistence (Batch Atomicity)
                    try {
                        database.runInTransaction {
                            val now = System.currentTimeMillis()
                            var batchDocsUpdated = 0
                            var batchConflicts = 0

                            batch.forEach { r ->
                                try {
                                    val existing = local.getById(r.id)

                                    // Conflict Detection
                                    if (existing != null && existing.syncStatus == SyncStatus.PENDING_UPDATE) {
                                        val localUpdatedAt = existing.updatedAt
                                        val remoteUpdatedAt = r.updatedRemoteAt ?: 0L

                                        if (remoteUpdatedAt > localUpdatedAt) {
                                            Log.w(TAG, "CONFLICT detected for ${r.id}. Remote($remoteUpdatedAt) > Local($localUpdatedAt)")

                                            // Create Conflict Entity
                                            val conflictEntity = com.are.distribuidora.data.local.entity.ProductConflictEntity(
                                                productId = r.id,
                                                remoteJson = serializeRemoteProduct(r),
                                                remoteUpdatedAt = remoteUpdatedAt,
                                                conflictDetectedAt = now
                                            )

                                            // Update Local to CONFLICT status
                                            local.handleConflict(r.id, conflictEntity)
                                            batchConflicts++
                                            return@forEach // Skip overwrite
                                        }
                                    }

                                    // Normal LWW / New Insert Logic
                                    // HARD DELETE check inside saveRemoteProductToLocal is acceptable,
                                    // but we can also do it here for clarity or use the helper.
                                    // Current helper `saveRemoteProductToLocal` blindly inserts/updates.
                                    // We need to upgrade it or handle delete here.

                                    // Let's handle it here to correspond with `saveLocalProducts` logic explicitly.
                                    if (r.isDeleted == true) {
                                         // Check timestamps if existing
                                         val remoteUpdatedAt = r.updatedRemoteAt ?: 0L
                                         val localUpdatedAt = existing?.updatedAt ?: 0L

                                         if (existing != null && remoteUpdatedAt >= localUpdatedAt) {
                                              Log.d(TAG, "syncDownstream: Remote is DELETED and newer. Performing HARD DELETE on ${r.id}")
                                              local.deleteInternal(r.id)
                                              batchDocsUpdated // Count as update/change
                                         } else if (existing == null) {
                                              Log.d(TAG, "syncDownstream: Remote is DELETED and not local. Skipping.")
                                         } else {
                                              Log.d(TAG, "syncDownstream: Remote is DELETED but older. Ignoring.")
                                         }
                                         return@forEach
                                    }

                                    saveRemoteProductToLocal(r, existing, now)
                                    batchDocsUpdated++

                                } catch (e: Exception) {
                                    Log.e(TAG, "Error processing item ${r.id} in batch", e)
                                    throw e // Trigger transaction rollback for this batch
                                }
                            }
                            totalUpdated += batchDocsUpdated
                            totalConflicts += batchConflicts
                            Log.d(TAG, "syncDownstream: Batch committed. Updated=$batchDocsUpdated, Conflicts=$batchConflicts")
                        }
                    } catch (e: Exception) {
                         Log.e(TAG, "Batch transaction failed", e)
                         throw e
                    }
                }
        } finally {
            val duration = System.currentTimeMillis() - startTime
            Log.i(TAG, "syncDownstream: Completed. Duration=${duration}ms, Batches=$totalBatches, Updated=$totalUpdated, Conflicts=$totalConflicts")
        }
    }

    private suspend fun saveRemoteProductToLocal(r: RemoteProduct, existing: com.are.distribuidora.data.local.entity.ProductEntity?, now: Long) {
        if (r.isDeleted == true) {
            // Should have been handled by caller, but safety check.
            Log.w(TAG, "saveRemoteProductToLocal called with isDeleted=true. Ignoring to prevent resurrection.")
            return
        }

         val entity = com.are.distribuidora.data.local.entity.ProductEntity(
            id = r.id,
            name = r.name,
            description = r.description,
            category = r.category,
            price = r.price ?: 0.0,
            imageUrl = r.imageUrl,
            barcode = r.barcode,
            stock = r.stock ?: 0,
            isActive = r.isActive ?: true,
            isDeleted = r.isDeleted ?: false,
            syncStatus = SyncStatus.SYNCED,
            createdAt = r.createdRemoteAt ?: 0L,
            updatedAt = r.updatedRemoteAt ?: 0L,
            lastSyncedAt = now
        )

        if (existing == null) {
            local.insert(entity)
        } else {
             // Strict LWW: Remote always wins (unless conflict detected above)
             if (entity.updatedAt >= existing.updatedAt) {
                 local.update(entity)
             } else {
                 Log.d(TAG, "Msg: Ignored stale remote update for ${r.id}")
             }
        }
    }

    private fun serializeRemoteProduct(r: RemoteProduct): String {
        return org.json.JSONObject().apply {
            put("id", r.id)
            put("name", r.name)
            put("price", r.price)
            put("stock", r.stock)
            put("updatedRemoteAt", r.updatedRemoteAt)
            // Add other fields as needed
        }.toString()
    }
}
